config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :categories, except: :show
  resources :products, path: '/'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products, dependent: :restrict_with_exception
end

app/models/product.rb
class Product < ApplicationRecord
  include PgSearch::Model
  pg_search_scope :search_full_text, against: {
    title: 'A',
    description: 'B'
  }

  ORDER_BY = {
    newest: "created_at DESC",
    expensive: "price DESC",
    cheapest: "price ASC"
  }

  has_one_attached :photo

  validates :title, presence: true
  validates :description, presence: true
  validates :price, presence: true

  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  around_action :switch_locale

  def switch_locale(&action)
    I18n.with_locale(locale_from_header, &action)
  end

  private

  def locale_from_header
    request.env['HTTP_ACCEPT_LANGUAGE']&.scan(/^[a-z]{2}/)&.first
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all.order(name: :asc)
  end

  def new
    @category = Category.new
  end

  def edit
    category
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to categories_url, notice: t('.created')
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if category.update(category_params)
      redirect_to categories_url, notice: t('.updated')
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    category.destroy

    redirect_to categories_url, notice: t('.destroyed')
  end

  private
    def category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @categories = Category.order(name: :asc).load_async
    @products = Product.with_attached_photo
    if params[:category_id]
      @products = @products.where(category_id: params[:category_id])
    end
    if params[:min_price].present?
      @products = @products.where("price >= ?", params[:min_price])
    end
    if params[:max_price].present?
      @products = @products.where("price <= ?", params[:max_price])
    end
    if params[:query_text].present?
      @products = @products.search_full_text(params[:query_text])
    end

    order_by = Product::ORDER_BY.fetch(params[:order_by]&.to_sym, Product::ORDER_BY[:newest])

    @products = @products.order(order_by).load_async
  end

  def show
    product
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to products_path, notice: t('.created')
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    product
  end

  def update
    if product.update(product_params)
      redirect_to products_path, notice: t('.updated')
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    product.destroy

    redirect_to products_path, notice: t('.destroyed'), status: :see_other
  end

  private

  def product_params
    params.require(:product).permit(:title, :description, :price, :photo, :category_id)
  end

  def product
    @product = Product.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
<div class="card container-fluid" style="max-width:319px;">
  <div class="card-body container-fluid">
<table class="table table-success table-striped table-sm">
  <thead>
    <tr>

    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= category.name %></td>
      <td><%= link_to t('.edit'), edit_category_path(category) %></td>
      <td>  <%= link_to t('.delete'), category_path(category), data: {
    turbo_method: :delete,
    turbo_confirm: t('common.confirm')
  } %></td>
  </tbody>
</table>
  </div>
  </div>


</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% @category.errors.full_messages.each do |error| %>
    <div>
      <%= error %>
    </div>
  <% end %>

  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<div class="section-title">
<h2><%= t('.title') %></h2>
</div>
<div class="card container-fluid" style="max-width:319px;">
  <div class="card-body container-fluid">
    <h5 class="card-title container-fluid">Añade una nueva categoría a los productos</h5>
<div class="section-title">
  <%= render "form", category: @category %>
<div>
  <%= link_to t('common.back'), categories_path %>
</div>
</div>
  </div>
</div> 

app/views/categories/index.html.erb
<h1><%= t('.title') %></h1>

<%= render partial: 'category', collection: @categories %>

<%= link_to t('.new'), new_category_path %>

app/views/categories/new.html.erb
<div class="section-title">
<h2><%= t('.title') %></h2>
</div>
<div class="card container-fluid" style="max-width:319px;">
  <div class="card-body container-fluid">
    <h5 class="card-title container-fluid">Añade una nueva categoría a los productos</h5>
<div class="section-title">
  <%= render "form", category: @category %>
<div>
  <%= link_to t('common.back'), categories_path %>
</div>
</div>
  </div>
</div> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shutko - Plásticos & Desechables</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/flash' %>
    <%= render 'shared/header' %>
    <%= yield %>
  </body>
</html>

app/views/products/_category.html.erb
<%= link_to products_path(category_id: category.id), class: 'category' do %>
<div class="badge rounded-pill bg-light text-dark">
  <%= category.name %>
</div>
<% end %>

app/views/products/_form.html.erb
<%= form_with model: @product do |form| %>
  <% @product.errors.full_messages.each do |error| %>
    <div>
      <%= error %>
    </div>
  <% end %>
<div class="card container-fluid" style="max-width:420px;">
  <div class="card-body container-fluid">
    <h5 class="card-title container-fluid">¡Agrega un nuevo producto al catálogo!</h5>
<div class="section-title">
  <div>
    <%= form.label :title %>
    <%= form.text_field :title, class:"form-control"%>
  </div>

  <div>
    <%= form.label :description %>
    <%= form.text_area :description, class:"form-control" %>
  </div>

  <div>
    <%= form.label :price %>
    <%= form.number_field :price, class:"form-control" %>
  </div>

  <div>
    <%= form.label :category_id %>
    <%= form.collection_select :category_id, Category.all.order(name: :asc), :id, :name %>
  </div>

  <div>
    <%= form.label :photo %>
    <%= form.file_field :photo %>
  </div>

  <%= form.submit %>
</div>
</div>
<% end %>

app/views/products/_product.html.erb
<div class="container">
<div class="card-deck">
<div class="card" style="max-width:319px;">
  <%= image_tag product.photo, width: 180 if product.photo.attached?%>
  <div class="card-body">
    <h2 class="card-title"><%= product.title %></h2>
    <p class="card-text"><%= product.price %>$.</p>

  <div class="card-body">
    <a href="#" class="card-link">Añada al carrito</a>
    <%= link_to product_path(product), class: 'product', 'data-turbo-frame': '_top' do %>
    <span>Ver producto</span>
  </div>
  </div>
</div>
</div>
</div>
<% end %>

app/views/products/edit.html.erb
<div class="section-title">
<h2><%= t('.title') %></h2>
</div>
<%= render 'form' %>

app/views/products/index.html.erb
<%= turbo_frame_tag 'categories' do %>
  
  <h3><%= t('.title') %></h3>

  <%= form_with url: products_path, method: :get do |form| %>
    <%= form.text_field :query_text, placeholder: t('.query_text'), onChange: 'this.form.requestSubmit()', value: params[:query_text] %>

    <%= form.number_field :min_price, placeholder: t('.min_price'), onChange: 'this.form.requestSubmit()', value: params[:min_price] %>

    <%= form.number_field :max_price, placeholder: t('.max_price'),onChange: 'this.form.requestSubmit()', value: params[:max_price] %>

    <%= form.select :order_by, options_for_select(Product::ORDER_BY.keys.map { |order| [t(".#{order}"), order] }, params[:order_by]), {}, { onChange: 'this.form.requestSubmit()' } %>
  <% end %>

  <%= link_to t('.all'), products_path %>

  <%= render partial: 'category', collection: @categories %>

  <div class="products">
    <%= render partial: 'product', collection: @products %>
  </div>


<% end %>

app/views/products/new.html.erb
<div class="section-title">
<h2><%= t('.title') %></h2>
</div>
<%= render 'form' %>

app/views/products/show.html.erb
<%= image_tag @product.photo, width: 250 if @product.photo.attached? %>

<h1 class='title'><%= @product.title %></h1>

<p class='description'><%= @product.description %></p>

<span class='price'><%= @product.price %>$</span>

<%= link_to t('.edit'), edit_product_path(@product) %>

<%= link_to t('.delete'), product_path(@product), data: {
  turbo_method: :delete,
  turbo_confirm: t('common.confirm')
} %>

app/views/shared/_flash.html.erb
<%= notice %>

<%= alert %>

app/views/shared/_header.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shutko - P&D</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>

<body>
  <header id="header" class="mb-5">
    <div class="container-fluid d-flex justify-content-between align-items">

      <a href="index.html" class="logo"><!-- <img src="assets/img/logo.png" alt="" class="img-fluid"> -->
      <%= link_to products_path do %>
      <h1>Shutko</h1>
      <% end %></p></h1></a>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">¡Busca y encuentra!</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <%= link_to t('.add'), new_product_path %>
            <li class="nav-item">
                <%= link_to t('Categorías'), categories_path %>
            </li>
              <li class="nav-item">
                <a class="nav-link" href="http://localhost:3000/products">Catálogo</a>
              </li>

            </ul>
              <form class="d-flex">
                <%= form_with url: products_path, method: :get do |form| %>
                <%= form.text_field :query_text, placeholder: ('Busca y encuentra.'), onChange: 'this.form.requestSubmit()', value: params[:query_text] %>
  <% end %>
                <button class="btn btn-outline-success" type="submit">Buscar</button>
              </form>
            </div>
          </div>
        </nav>


        <nav id="navbar" class="navbar order-last order-lg-0">
          <ul>
            <li><a class="active" href="index.html"><i class="bi bi-cart3"> Carrito</i></a></li>
            <li> <i class="nav-item bi bi-person-circle">
             <% if user_signed_in? %>
             <%= link_to(current_user.email, edit_user_registration_path, class: "nav-link bi bi-person-circle") %>
             <% else %>
             <%= link_to("Iniciar sesión", new_user_registration_path, class: "nav-link bi bi-person-circle") %>
             <% end %>
           </li>
           <li><div class="dropdown">

           </div>
         </li>
       </ul>
       <i class="bi bi-list mobile-nav-toggle"></i>
     </nav>

   </div>

 </header>
 <!-- <%= yield %> -->
 <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
 <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
</body>
</html>